title: Slickmind - The Blog
description: Dive into the world of Artificial Intelligence, Robotics and Intelligent transportation systems. Find solutions to numerous unanswered questions.

url: "http://slickmind.in"
enforce_ssl: "slickmind.in"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 # - title: About
 #   url: /about
 # - title: Contact
 #   url: /contact

social:
   github: nitesh4146
   twitter: nitesh4146
   email: contact@guptanitish.com

google_analytics: "UA-117432219-2"
