title: Slickmind - The Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: "http://slickmind.in"
enforce_ssl: "slickmind.in"
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: nitesh4146
   twitter: nitesh4146
   email: nitesh4146@gmail.com

google_analytics: "UA-58263416-1"
